### ISSUE TITLE
discussion on config files -currency and abbrev

### ISSUE THREAD

**Issue by Irishx** [LanguageMachines/uctodata#11]
Why is the list of currency so small and arbitrary? The signs $ £ btc could be added, for example?
The tokenizer does split the numbers from the signs in a consistent manner (whether they are in the config-file or not)
fl90,- -> fl 90 , - 
$90,-  -> $ 90 , - 
Do we want one currency rule file for all languages? Or, just mention in the manual that users could add their own list if they are interested in finding money expressions in the text?

I think that most users are not aware of the enriched ucto output that vould be useful for NER!

There are separate abbreviation files for  Dutch, Spanish and Portuguese but for the other languages they are stored inline in the configuration files. Would it not be better to have them all in the same way?

**Comment by kosloot** [comment]
these are several issues. better to have them separated maybe...

anyway: 
$ £ etc. DON't need to be added, as the CURRENCY rule states:
``CURRENCY=^(\p{Sc}|%CURRENCY%)(?:\p{N}|\Z)``
in this regular expression, ``p{Sc}`` denotes a wealth of currency symbols.
(see [here](https://en.wikipedia.org/wiki/Unicode_character_property) )
The ``%CURRENCY%`` part just makes it possible to add some extra symbols, if desired.

Having abbreviations in a separate file is desirable, i think, as this list can be very long.
Its is a small task to create such lists and add them to the configuration.

**Comment by proycon** [comment]
> Having abbreviations in a separate file is desirable, i think

Agreed.

**Comment by kosloot** [comment]
I created .abr files for Turkish , Swedish, Frysk and Russian

Most of this files are rudimentary. An abbreviation file for french is missing!
